### PR TITLE
Nazi logo removed

### PR DESCRIPTION
**Pull request by gagarin55**
This PR removes image which actually is the copy from "3rd reich eagle" used as Nazi logo during WW II

### CODE REVIEW

**Comment by sjmackenzie** [comment]
Ha! Let me bounce this off the ETC mascot group! Oh man

**Comment by sjmackenzie** [comment]
Ha! Let me bounce this off the ETC mascot group! Oh man

**Comment by ghost** [comment]
Nazi LOL

**Comment by sjmackenzie** [comment]
On initial thoughts (waiting for the community to respond) these are just mockups and probably no need for a severe "censor this" cause it's not politically correct. How about instead adding a comment along the lines of "Cons: resembles a third reich nazi symbol" . This way we can keep it for historical accuracy and the final version will certainly be modified so that it does not resemble such a symbol! Thanks for the observation!

**Comment by ghost** [comment]
@sjmackenzie  So you are saying are there Hydras in etc-dev team or something?

**Comment by sjmackenzie** [comment]
I have no idea what you mean, no one from etcdev participated in this mascot. There has been a lot of work that's gone into these images so far, I just don't see the need for a knee jerk reaction to remove it, instead just use it as empirical evidence of progress towards a suitable logo. This represents yet another mistake, and that should be preserved for historical accuracy. It could well mean there needs to be another vote (by the financial backers) to vote another mockup logo. Let's see what happens over the next few days.

**Comment by sjmackenzie** [comment]
I'm going to close this because the main working group are those that contributed to the mascot funding and have a say (as agreed on by the group) on what happens to the design. Thanks for alerting us to this. Let's see what else guabano can come up with!

**Comment by drd34d** [comment]
"copy from 3rd reich eagle" is a huge exageration. Any imagery with a bird shaped open wing figure could resemble it but that doesn't mean all eagle/phoenix/bird logos with open wings and frontal view are nazi symbols.

**Comment by OmniEdge** [comment]
@gagarin55  lol. I like an awkward sense of humour especially on a Monday morning! But it's....

A-well-a ev'rybody's heard about the bird
B-b-b-bird, b-birdd's a word
A-well, a bird, bird, bird, bird is a word
A-well, a bird, bird, bird, well-a bird is a word
A-well, a bird, bird, bird, b-bird's a word 

;-) Don't make fun of our bird. It's a hottest phoenix around!

**Pull request closed without merging**
